### ISSUE TITLE
Using the sdk for Project Management 

### ISSUE THREAD

**Issue by MattNolf** [launchdarkly/go-server-sdk#13]
Hi, I'm wondering if there will be any support to programatically manage projects using the go-server-sdk - to provide support for operations such as:

- Updating user flag settings
- Creating/Patching segments

E.g:
```
func UpdateUserFlagSetting(user User, flag FeatureFlag, value interface{}) error
```

Thanks

**Comment by bwoskow-ld** [comment]
Hi @MattNolf ,

Thanks for the suggestion. At the moment we don't have any plans to modify go-server-sdk (or our other SDKs for that matter) to add support for operations like this.

That said, LaunchDarkly's REST API supports these operations and you are free to write your own lightweight HTTP client layer in your application to meet your requirements. Our API is [fully documented](https://apidocs.launchdarkly.com) -- in particular, take a look at [update feature flag](https://apidocs.launchdarkly.com/reference#update-feature-flag) and [create segment](https://apidocs.launchdarkly.com/reference#create-segment) sections.

Let us know how it goes!

**Comment by bwoskow-ld** [comment]
Hi @MattNolf,

A colleague of mine reminded me just now of https://github.com/launchdarkly/api-client-go which is a Go client library for our REST API. You should be able to use that library to meet your needs.

If you have any questions regarding the client library, please file a follow-up issue on that repository. With this in mind, I'm going to go ahead and close this request.
