### ISSUE TITLE
Support for realtime updates for features flags

### ISSUE THREAD

**Issue by muravjov** [launchdarkly/go-server-sdk#43]
**Is your feature request related to a problem? Please describe.**
I have a feature flag, e.g. "multiplier" and I want to be notified in my Go app when that flag has been changed.

I see how I may implement it in client side JS, see "Streaming Updates" and *.on('change')* method.

https://docs.launchdarkly.com/sdk/client-side/javascript#code-sample

I see no such API in go-server-sdk (and sources), it is not there, right?
One (long) way now to do it is to patch/fork *inMemoryDataStore* type code.

**Describe the solution you'd like**
I would like to have some *channel* API solution or function based like
```
ldClient.OnChange(func(name string, value interface{}) {
    ...
})
```

**Describe alternatives you've considered**
I just searched the sources and see there is no way to make use of realtime updates without a lot of coding.

**Comment by eli-darkly** [comment]
That feature was added in the 5.0.0 release. See: https://pkg.go.dev/gopkg.in/launchdarkly/go-server-sdk.v5#LDClient.GetFlagTracker

**Comment by muravjov** [comment]
Yes, found that code in the course of patching inMemoryDataStore

Maybe update the documentation at https://docs.launchdarkly.com/sdk/server-side/go?

Code snippet:
```
			ch := ldClient.GetFlagTracker().AddFlagChangeListener()
			//defer ldClient.GetFlagTracker().RemoveFlagChangeListener(ch)

			for e := range ch {
				if _, ok := parameters[e.Key]; !ok {
					continue
				}

				val, err := ldClient.Float64Variation(e.Key, user, 0)
				if err != nil {
					continue
				}

				parameters[e.Key] = val
				updateParametersMetric()
			}

```

**Comment by eli-darkly** [comment]
Yes, we should update that reference guide page - sorry for the omission. However, as a general rule, those pages are only a general summary of SDK functionality. The API reference on pkg.go.dev is the place to look for the complete set of client features, so it's best to start by looking at the regular API before delving into low-level implementation details to implement a workaround.
