### ISSUE TITLE
Noisy `waitForEvents` log in `ldfilewatch`

### ISSUE THREAD

**Issue by dstrelau** [launchdarkly/go-server-sdk#48]
Hi there!

[This line in `ldfilewatch.(*fileWatcher).waitForEvents`](https://github.com/launchdarkly/go-server-sdk/blob/v5/ldfilewatch/watched_file_data_source.go#L98) sure looks like something that should be at Debug level instead. As is, it spits out a few of that log line every time you modify the watched file.

Happy to submit a quick PR if you'd like. Thanks!

**Comment by eli-darkly** [comment]
Actually it looks like something that was left in by mistake during development. Thanks for catching this - we'll take care of it.

**Comment by dstrelau** [comment]
Thanks!
