### ISSUE TITLE
Expose client.variation method

### ISSUE THREAD

**Issue by phoenix2x** [launchdarkly/go-server-sdk#73]
**Is your feature request related to a problem? Please describe.**
We have a use case where we don't know the flag type in advance. Unfortunately, ldclient exposes only type-specific `XXXVariation` methods. It would be nice to have a way to examine type ourselves.

**Describe the solution you'd like**
The simplest one is to expose [variation](https://github.com/launchdarkly/go-server-sdk/blob/0880f8480e0eb3712248833fbd4ed6aaa204a4e1/ldclient.go#L826) method that returns (ldreason.EvaluationDetail, error) and allows users to deal with types.

**Describe alternatives you've considered**
Right now we have to use a workaround. Call `StringVariationDetail` and if the error kind is `WRONG_TYPE` call the following method for example `BoolVariationDetail`, etc.

**Comment by cwaldren-ld** [comment]
Hi @phoenix2x , thank you for the request. 

Let me first ask - have you tried using the [JSONVariation API](https://github.com/launchdarkly/go-server-sdk/blob/v5/ldclient.go#L743), which may satisfy your requirements?

**Comment by phoenix2x** [comment]
Hi @cwaldren-ld,

Thank you for the quick response. Yes, JSONVariation works for us.

Do you think it's a workaround that relies on implementation detail(the lack of type check in the JSONVariation method) or it's a feature? When I see the JSONVariation method, I think about JSON flag variation in launchdarkly UI:) Curious if you're planning to expose a generic Variation method.

Thank you.

**Comment by cwaldren-ld** [comment]
Hi @phoenix2x , `JSONVariation` is a legitimate feature of the library, please feel free to use it! ([docs #1](https://docs.launchdarkly.com/sdk/features/evaluating#go), [docs #2](https://pkg.go.dev/gopkg.in/launchdarkly/go-server-sdk.v5#LDClient.JSONVariation)). 

The return value, which is an `ldvalue.Value`, can hold any value representable within the LaunchDarkly system.

As for generics, are you referring to the Go language's new [generics](https://go.dev/doc/tutorial/generics) feature, or something else?

**Comment by phoenix2x** [comment]
Hi @cwaldren-ld , I guess I need to clarify myself:) 
The confusion comes from an uncanny resemblance between `XXXVariation` methods and `variation types` in the app.launchdarckly.com. It's not very intuitive that `JSONVariation` method can be used to evaluate `Boolean` `variation type` for example. So I was asking to have `Variation`(without type prefix) method that quickly tells the user that it can be used for any configured `variation type`.

<img width="652" alt="image" src="https://user-images.githubusercontent.com/6801277/172697288-a95ffd95-18de-4291-a331-aeb3e99f0e50.png">
<img width="792" alt="image" src="https://user-images.githubusercontent.com/6801277/172697772-ea473b35-cf80-43bc-a831-eafec89c869b.png">

**Comment by eli-darkly** [comment]
As the documentation says, the `JSONVariation` method _can be any JSON type_. Boolean, number, and string are all JSON types. The fact that the JSONVariation method doesn't do type checking is not an implementation detail; it's the definition of the method, so yes you can rely on it.

I think the source of the confusion here is that when the dropdown menu in the UI says "JSON", it really means "JSON data that isn't one of those simple types." There's a separate option for that simply because otherwise if you typed something like `["a"]`, it wouldn't know whether you meant "a JSON array containing a string value 'a'", or "a string consisting of the characters `[`, `"`, `a`, `"`, `]`", either of which would be valid as a flag variation value.

**Comment by eli-darkly** [comment]
I myself would prefer to have the UI present this differently, and it's been raised as an issue before— as has the idea of renaming the SDK methods to something like "AnyTypeVariation". So I don't mean to say that this is not confusing or that there's no reason for you to have interpreted it that way. However, technically it is correct to say that a boolean value is a JSON value; fundamentally the LD data model, when it comes to flag variations, is defined in terms of JSON and that is one of the basic features of the JSON spec.

**Comment by phoenix2x** [comment]
Hi @eli-darkly,

Sure, I'm not saying it's not correct. Just saying that you could spare your time doing more pleasant things than chatting with me if the UI and/or SDK methods were more intuitive:) If you keep receiving feedback like this maybe it's worth changing something.

Thank you.

**Comment by cwaldren-ld** [comment]
Thanks again @phoenix2x for submitting this request!

Tracking internally as _156573_.
