### ISSUE TITLE
List Feature Flags

### ISSUE THREAD

**Issue by domgreen** [launchdarkly/go-server-sdk#76]
**Is your feature request related to a problem? Please describe.**
As part of LaunchDarklys API clients are able to call ListFlags [link](https://apidocs.launchdarkly.com/tag/Feature-flags#operation/getFeatureFlags). It would be good to have the same functionality, the ability to pull a list of flags by type and by specific tag.

**Describe the solution you'd like**

The SDK has the ability to List Flags as the API does.

**Describe alternatives you've considered**

N/A

**Comment by eli-darkly** [comment]
Hi. We don't provide this in the SDKs for the exact reason you mentioned: it's in the API clients, and that's what the API clients are for. The SDKs are designed specifically to _use_ feature flags, with the assumption being that the application already knows what the flags are supposed to be. The service endpoints that they communicate with do not have any knowledge of things like flag types/tags.
