### ISSUE TITLE
List feature flags with each flag's details 

### ISSUE THREAD

**Issue by hanpengwang** [launchdarkly/go-server-sdk#79]
Out team needs to find get all feature flags and flag's all variations.
We only found this in the [REST API docs](https://apidocs.launchdarkly.com/tag/Feature-flags/#operation/getFeatureFlags)

So would be possible for our SDK to have more features that show in rest api?

**Comment by eli-darkly** [comment]
The SDK libraries are deliberately _not_ implemented as clients for the entire LaunchDarkly REST API. There are generated API clients for that, such as https://github.com/launchdarkly/api-client-go.

The SDKs are focused on the core functionality of evaluating feature flags and generating analytics events. They connect to a small number of API endpoints that are specifically for use by the SDKs, which use the SDK key as a credential. The other REST API that you're talking about uses an entirely different credential for security reasons, and it doesn't have the same purpose— it corresponds to all of the things you can do on the LD dashboard.
