### ISSUE TITLE
Support client side keys

### ISSUE THREAD

**Issue by c4milo** [launchdarkly/go-server-sdk#93]
We have a strong use case for using feature flags from our cloud platform CLI. However, this CLI runs in untrusted environments and we would like to avoid leaking our server-side SDK Key. This ticket is to kindly request supporting client side SDK keys.

**Comment by cwaldren-ld** [comment]
Hi @c4milo, I believe what you are asking for is a Go Client-side SDK. We currently have one in the works, but it is not released yet. 

We will follow up when more information is available.

**Comment by c4milo** [comment]
@cwaldren-ld, that's great to hear. Is there a timeline you would be able to share or should we ask our LD account manager?

**Comment by cwaldren-ld** [comment]
@c4milo  I cannot share any timeline, but please do follow-up with your account manager. Thank you.
