### ISSUE TITLE
Refined error handling and management

### ISSUE THREAD

**Issue by sonasingh46** [launchdarkly/go-server-sdk#98]
**Is this a support request?**
No

**Describe the bug**
The error returned from the launch darkly SDK client should have proper HTTP error codes. Additionally, the SDK should have utility functions to figure out what kind of error it was e.g. 
```
err, flagVal := client.ResolveBool()
 
IsFlagNotFoundError(err error) bool {} // this should return true or false based on if error was flag found or not

GettErrorCode(err) int32 () // this should return the error code of the returned error

At places where http codes is not suitable localised error code for the SDK client should be developed. 

For example, LD40001 could be an error code for invalid characters in SDK key.

```

We'd like to treat errors differently in our backend application that relies on LaunchDarkly: for example, if we get a 400 from LaunchDarkly we likely want to return a 500 to the user. But if we get a 503 or a network error we could react differently and return a different error to our users.

**To reproduce**
N/A

**Expected behavior**
N/A

**Logs**
N/A

**SDK version**
V6

**Language version, developer tools**
For instance, Go 1.11 or Ruby 2.5.3. If you are using a language that requires a separate compiler, such as C, please include the name and version of the compiler too.

**OS/platform**
For instance, Ubuntu 16.04, Windows 10, or Android 4.0.3. If your code is running in a browser, please also include the browser type and version.

**Additional context**

**Comment by cwaldren-ld** [comment]
Hi @sonasingh46, I want to be sure I understand your request.

To be clear, the SDK **does not** make individual HTTP requests when you call `BoolVariation`, `StringVariation`, like you possibly imply with `err, flagVal := ResolveBool`. 

By default, the SDK downloads all flag data from LaunchDarkly when it first starts.

When you make a `Variation` call, it is performing some computations with the data that already exists. There is no individual network call to obtain the data. 

If you'd like more information on why a certain result was returned, use the `VariationDetail` methods. 

For example, `BoolVariationDetail` returns an extra "Details" structure containing the evaluation reason. For your case, [it will tell you if the flag was missing.](https://pkg.go.dev/github.com/launchdarkly/go-sdk-common/v3/ldreason#EvalErrorKind) (`EvalErrorFlagNotFound`).

See [here](https://docs.launchdarkly.com/sdk/features/evaluation-reasons#go) for more information and an example.

Additionally, `MakeClient` returns an error value if there was a "permanent" issue connecting to LaunchDarkly (such as incorrect SDK key.) If the error isn't permanent (like a temporary HTTP issue), then the SDK attempts to reconnect automatically in the background.

If you'd like to know more information about that process, you can check the [DataSourceStatusProvider](https://pkg.go.dev/github.com/launchdarkly/go-server-sdk/v6#LDClient.GetDataStoreStatusProvider).

Let me know if this suits your needs. We can continue discussing.

**Comment by sonasingh46** [comment]
Hey @cwaldren-ld -- Thank you for the response. 

So you are saying only once in the lifetime( of the process using SDK) the LaunchDarkly data gets downloaded and that is the only HTTP call that happens. And rest of all the evaluation happens from the in memory data? 

Sure. So the next question is -- even if there is some change to the flag in launch darkly -- it won't be reflected until the process restarts and downloads again. Or does sdk client periodically tries to download and update the downloaded data?

**Comment by sonasingh46** [comment]
I tried to do a simple test as the following: 
- created a test flag and enabled it to return `true`
- read the flag from a go program using go-sdk in an infinite for loop. It printed the flag value as `true` as expected.
- changed the  flag value to `false` to disable it.
- the program printed the flag value to `false` without actually restarting it, which is great. 

So the question is -- does the launch darkly sdk updates the local data/cache periodically? Also, can you point me to the doc where I can find more info re this.

**Comment by sonasingh46** [comment]
Also, I am trying to tune logging a bit and want to pass my own logger instance to log. Can't find any examples or instructions on the docs. 

Also one instruction in the doc is incorrect as the `BaseLogger ` method is not there which is mentioned in the docs.
https://docs.launchdarkly.com/sdk/features/logging#go

**Comment by cwaldren-ld** [comment]
Hey @sonasingh46 , sorry for the delay in my reply.

> So you are saying only once in the lifetime( of the process using SDK) the LaunchDarkly data gets downloaded and that is the only HTTP call that happens. And rest of all the evaluation happens from the in memory data?

Not quite. It maintains a long-lived HTTP connection using [Server-Sent-Event](https://en.wikipedia.org/wiki/Server-sent_events) protocol. When the SDK first starts, it receives all flag rules in one big payload. At this point, the SDK is capable of evaluating any flag in an environment. 

> So the next question is -- even if there is some change to the flag in launch darkly -- it won't be reflected until the process restarts and downloads again.

As flag rules are changed via LaunchDarkly UI, those changes are streamed from LaunchDarkly to the SDK over same HTTP connection (as you saw in your test.) 

This means when you are evaluating flags, you are nearly always evaluating the latest configuration (no more than a couple hundred milliseconds old) - but it's not causing any additional HTTP requests to be made.

> Can you point me to the doc where I can find more info re this.

https://launchdarkly.com/how-it-works/

**Comment by cwaldren-ld** [comment]
As for your question about logging, thanks for pointing out the issue on our docs site - it is out of date. 

You could configure a custom logger like this:
```go
type myLogger struct {
}

func (m *myLogger) Println(values ...interface{}) {
	fmt.Println(values)
}

func (m *myLogger) Printf(format string, values ...interface{}) {
	fmt.Printf(format, values)
}

func main() {
  // Omitting the SDK creation here to keep the example simple.
  loggers := ldlog.NewDefaultLoggers()
  loggers.SetBaseLogger(&myLogger{})

   cfg := ld.Config{
      Logging: ldcomponents.Logging().Loggers(loggers)
   }
}
```

Read more in [our SDK docs](https://pkg.go.dev/github.com/launchdarkly/go-sdk-common/v3/ldlog#Loggers).
